#!/bin/bash
export TARGET=../src/main/webapp
export HOME=`pwd`

cd $TARGET

resources/js/lib/closure/closure/bin/calcdeps.py \
-c ../../../tools/closure.jar \
-d resources/js/lib/closure/closure/ \
-p resources/js/lib/radio/ \
-o deps > resources/js/lib/deps.js

cd $HOME
