#!/bin/bash
PROJECT="your_project"
TARGET=../src/main/webapp
HOME=`pwd`

cd $TARGET

js/lib/closure/closure/bin/calcdeps.py \
-c ../../../tools/closure.jar \
-d js/lib/closure/closure/ \
-p js/lib/$PROJECT/ \
-o deps > js/lib/deps.js

cd $HOME
